### ISSUE TITLE
Choice for website version leads to crashes

### ISSUE THREAD

**Issue by johanw666** [sigx/sig4a#17]
Sig4a sometimes crashes on my device, I think it is caused by building the website version but not (completely) removing the apk update functionality. Logfile: https://debuglogs.org/eab6336b71a6f649aaa3169e42ef72bcec257864e7fe0733d9aa88bb3fb03e1d

The relevant part is(I think):
```
--------- beginning of crash
07-27 17:28:03.531 12108 12108 E AndroidRuntime: FATAL EXCEPTION: main
07-27 17:28:03.531 12108 12108 E AndroidRuntime: Process: com.github.sigx.sig4a, PID: 12108
07-27 17:28:03.531 12108 12108 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate receiver com.github.sigx.sig4a.service.UpdateApkRefreshListener: java.lang.ClassNotFoundException: Didn't find class "com.github.sigx.sig4a.service.UpdateApkRefreshListener" on path: DexPathList[[zip file "/data/app/com.github.sigx.sig4a-2/base.apk"],nativeLibraryDirectories=[/data/app/com.github.sigx.sig4a-2/lib/arm, /data/app/com.github.sigx.sig4a-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2754)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(<Xposed>)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:154)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1468)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:234)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5526)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
07-27 17:28:03.531 12108 12108 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class 
```

**Comment by five-c-d** [comment]
I have seen this in @nuttso's debuglogs, as well.  Will add the link when I find which ones I saw it in.  

Not positive I've ever seen it myself however?  Two test handsets with stock ROMs

> not (completely) removing the apk update function

I also suspect this is the root cause.  But I think there is something to do with non-standard ROMs that comes into play (xposed in your case Johan and graphene+MDM for nuttso).

**Comment by valldrac** [comment]
Both are right. I was sure I had disabled automatic updates... obviously I forgot to do it. Thanks to this bug the updater always crashes and never completes an update.
