### ISSUE TITLE
upstream:  AvatarImageView.setAvatar() causes appcrash w/ "You cannot start a load for a destroyed activity"

### ISSUE THREAD

**Issue by five-c-d** [sigx/sig4a#4]
There is an app-crash bug in 4.42.1 aka x1pre3 and x1pre4, but Greyson patched it up in 4.42.2 just a couple days ago.  So ignore this bug-report, we will be re-pinning unto that-or-later in a couple days.  

<details><summary>for the historical record... in case somebody else hits this crash</summary><p>

Here is Greyson's patch == https://github.com/signalapp/Signal-Android/commit/5948b46ac74368c66724ed0d11c8fe809998bba6 , here is the stacktrace in case anybody running 4.42.1 hits it.  This is from android 7.1.1 running sigGesT-4.42.1-x1pre3 shortly after the app-crash == https://debuglogs.org/9de3cf67e599bdb0d3d5489481068395a5f07f1beab26e43235f20a2d550c0f2

```
1	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
2	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:323)
3	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:157)
4	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:186)
5	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at com.bumptech.glide.Glide.with(Glide.java:801)
NEW6~~	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.mms.GlideApp.with(GlideApp.java:129)
new7~~	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.components.AvatarImageView.setAvatar(AvatarImageView.java:108)			== bug was here  , needed requestManager instead of raw GlideApp.with
new8~~	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationItem.setContactPhoto(ConversationItem.java:732)
new9~~	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.ConversationItem.lambda$onModified$10(ConversationItem.java:1036)
10~~	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at org.thoughtcrime.securesms.conversation.-$$Lambda$ConversationItem$tiqTDY_HZjvoLuDZaRbfDz9euj8.run(lambda)
11	2019-06-22 14:22:38.460 CDT E UncaughtExceptionLogger: 	at android.os.Handler.handleCallback(Handler.java:751)
```

There was a very similar old GlideApp bug in May 2015 reported by moxie0 at https://github.com/signalapp/Signal-Android/issues/3110 ... which mcginty fixed with https://github.com/mcginty/TextSecure/commit/7a21f332427ddb3e6da78f9315df57630df19917 

```
1	java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
2	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:133)
3	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:101)
4	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:86)
5	at com.bumptech.glide.Glide.with(Glide.java:609)
6	at org.thoughtcrime.securesms.components.ThumbnailView.buildEncryptedPartGlideRequest(ThumbnailView.java:114)
7	at org.thoughtcrime.securesms.components.ThumbnailView.buildThumbnailGlideRequest(ThumbnailView.java:99)
8	at org.thoughtcrime.securesms.components.ThumbnailView.buildGlideRequest(ThumbnailView.java:80)
9	at org.thoughtcrime.securesms.components.ThumbnailView.setImageResource(ThumbnailView.java:60)			== bug was here  , needed isContextValid ... also needed onDetachedFromWindow meth which calls Glide.clear
10	at org.thoughtcrime.securesms.components.ThumbnailView$SlideDeckListener$1.run(ThumbnailView.java:140)
11	at android.os.Handler.handleCallback(Handler.java:739)
```

</p></details>

**Comment by five-c-d** [comment]
fixed in 4.42.2 upstream
